STOCK_OPTIONS = [
    {"ticker": "AAPL", "name": "Apple"},
    {"ticker": "MSFT", "name": "Microsoft"},
    {"ticker": "GOOGL", "name": "Alphabet"},
    {"ticker": "AMZN", "name": "Amazon"},
    {"ticker": "NVDA", "name": "NVIDIA"},
    {"ticker": "META", "name": "Meta Platforms"},
    {"ticker": "TSLA", "name": "Tesla"},
    {"ticker": "BRK-B", "name": "Berkshire Hathaway"},
    {"ticker": "JPM", "name": "JPMorgan Chase"},
    {"ticker": "V", "name": "Visa"},
    {"ticker": "UNH", "name": "UnitedHealth Group"},
    {"ticker": "XOM", "name": "Exxon Mobil"},
    {"ticker": "LLY", "name": "Eli Lilly"},
    {"ticker": "WMT", "name": "Walmart"},
    {"ticker": "MA", "name": "Mastercard"},
    {"ticker": "PG", "name": "Procter & Gamble"},
    {"ticker": "JNJ", "name": "Johnson & Johnson"},
    {"ticker": "HD", "name": "Home Depot"},
    {"ticker": "COST", "name": "Costco"},
    {"ticker": "ORCL", "name": "Oracle"},
    {"ticker": "ABBV", "name": "AbbVie"},
    {"ticker": "BAC", "name": "Bank of America"},
    {"ticker": "KO", "name": "Coca-Cola"},
    {"ticker": "AVGO", "name": "Broadcom"},
    {"ticker": "PEP", "name": "PepsiCo"},
    {"ticker": "MRK", "name": "Merck"},
    {"ticker": "CRM", "name": "Salesforce"},
    {"ticker": "ADBE", "name": "Adobe"},
    {"ticker": "NFLX", "name": "Netflix"},
    {"ticker": "AMD", "name": "Advanced Micro Devices"},
    {"ticker": "INTC", "name": "Intel"},
    {"ticker": "CSCO", "name": "Cisco"},
    {"ticker": "DIS", "name": "Walt Disney"},
    {"ticker": "MCD", "name": "McDonald's"},
    {"ticker": "NKE", "name": "Nike"},
    {"ticker": "T", "name": "AT&T"},
    {"ticker": "VZ", "name": "Verizon"},
    {"ticker": "PFE", "name": "Pfizer"},
    {"ticker": "BA", "name": "Boeing"},
    {"ticker": "CAT", "name": "Caterpillar"},
    {"ticker": "GE", "name": "GE Aerospace"},
    {"ticker": "GM", "name": "General Motors"},
    {"ticker": "F", "name": "Ford"},
    {"ticker": "UBER", "name": "Uber"},
    {"ticker": "SHOP", "name": "Shopify"},
    {"ticker": "PYPL", "name": "PayPal"},
    {"ticker": "SQ", "name": "Block"},
    {"ticker": "AMC", "name": "AMC Entertainment"},
    {"ticker": "PLTR", "name": "Palantir"},
    {"ticker": "SNOW", "name": "Snowflake"},
]

VALID_TICKERS = {stock["ticker"] for stock in STOCK_OPTIONS}
